### ISSUE TITLE
I got an error running the ng serve command, how do I fix it

### ISSUE THREAD

**Issue by Zxce3** [wizdmio/wizdm#37]
I got an error running the ```ng serve``` command, how to fix it and the log below.
```sh
[error] Error: The /home/memet/projek/wizdm/wizdm/src/environments/secrets.private.ts path in file replacements does not exist.
    at Object.normalizeFileReplacements (/home/memet/projek/wizdm/node_modules/@angular-devkit/build-angular/src/utils/normalize-file-replacements.js:26:19)
    at Object.normalizeBrowserSchema (/home/memet/projek/wizdm/node_modules/@angular-devkit/build-angular/src/utils/normalize-builder-schema.js:22:57)
    at generateBrowserWebpackConfigFromContext (/home/memet/projek/wizdm/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:153:39)
    at async Object.generateI18nBrowserWebpackConfigFromContext (/home/memet/projek/wizdm/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:95:20)
    at async setup (/home/memet/projek/wizdm/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:78:47)

```
i'm noobie
btw thanks for a great repo

**Comment by paulayo93** [comment]
Have you been able to resolve the issue? @Zxce3
